-- Task 4: Baseline analytics queries

-- 4a: Document count grouped by source identifier
WITH expanded AS (
  SELECT
    dm.DOCUMENT_URL,
    f.VALUE::STRING AS SOURCE_IDENTIFIER
  FROM IDENTIFIER('{DOCS_MASTER}') dm,
       LATERAL FLATTEN(input => dm.SOURCES) f
)
SELECT
  SOURCE_IDENTIFIER,
  COUNT(*) AS DOCUMENT_COUNT
FROM expanded
GROUP BY SOURCE_IDENTIFIER
ORDER BY DOCUMENT_COUNT DESC, SOURCE_IDENTIFIER;

-- 4b: Monthly document distribution (trailing 12 months by LASTMOD month)
WITH months AS (
  SELECT DATE_TRUNC('month', DATEADD('month', -SEQ4(), CURRENT_DATE()))::DATE AS MONTH_START
  FROM TABLE(GENERATOR(ROWCOUNT => 12))
),
counts AS (
  SELECT
    DATE_TRUNC('month', COALESCE(LASTMOD, FIRST_SEEN_AT))::DATE AS MONTH_START,
    COUNT(*) AS DOCUMENT_COUNT
  FROM IDENTIFIER('{DOCS_MASTER}')
  WHERE COALESCE(LASTMOD, FIRST_SEEN_AT) IS NOT NULL
  GROUP BY 1
)
SELECT
  m.MONTH_START,
  COALESCE(c.DOCUMENT_COUNT, 0) AS DOCUMENT_COUNT
FROM months m
LEFT JOIN counts c USING (MONTH_START)
ORDER BY MONTH_START;

-- 4c: Content fetch success rate segmented by source
WITH expanded AS (
  SELECT
    dm.DOCUMENT_URL,
    f.VALUE::STRING AS SOURCE_IDENTIFIER
  FROM IDENTIFIER('{DOCS_MASTER}') dm,
       LATERAL FLATTEN(input => dm.SOURCES) f
),
joined AS (
  SELECT
    e.SOURCE_IDENTIFIER,
    e.DOCUMENT_URL,
    dc.LAST_FETCH_STATUS,
    dc.LAST_SUCCESS_AT
  FROM expanded e
  LEFT JOIN IDENTIFIER('{DOCUMENT_CONTENT}') dc
    ON dc.DOCUMENT_URL = e.DOCUMENT_URL
)
SELECT
  SOURCE_IDENTIFIER,
  COUNT(*) AS URL_COUNT,
  COUNT_IF(LAST_FETCH_STATUS = 'SUCCESS' OR LAST_SUCCESS_AT IS NOT NULL) AS SUCCESS_URL_COUNT,
  (COUNT_IF(LAST_FETCH_STATUS = 'SUCCESS' OR LAST_SUCCESS_AT IS NOT NULL) / NULLIF(COUNT(*), 0))::FLOAT AS SUCCESS_RATE
FROM joined
GROUP BY SOURCE_IDENTIFIER
ORDER BY SUCCESS_RATE DESC, URL_COUNT DESC, SOURCE_IDENTIFIER;

-- 4d: Top 10 URL path segments (first path component after domain)
WITH segments AS (
  SELECT
    COALESCE(
      NULLIF(SPLIT_PART(PARSE_URL(DOCUMENT_URL):path::STRING, '/', 2), ''),
      '(root)'
    ) AS FIRST_PATH_SEGMENT
  FROM IDENTIFIER('{DOCS_MASTER}')
)
SELECT
  FIRST_PATH_SEGMENT,
  COUNT(*) AS URL_COUNT
FROM segments
GROUP BY FIRST_PATH_SEGMENT
ORDER BY URL_COUNT DESC, FIRST_PATH_SEGMENT
LIMIT 10;

-- 4e: Stale documents (LASTMOD older than 180 days)
-- 4e: Stale documents (LASTMOD older than 180 days)
SELECT
  COUNT_IF(DATEDIFF('day', COALESCE(LASTMOD, FIRST_SEEN_AT)::DATE, CURRENT_DATE()) >= 180) AS STALE_COUNT,
  COUNT(*) AS TOTAL_WITH_LASTMOD,
  COALESCE(
    COUNT_IF(DATEDIFF('day', COALESCE(LASTMOD, FIRST_SEEN_AT)::DATE, CURRENT_DATE()) >= 180) 
    / NULLIF(COUNT(*), 0),
    0
  )::FLOAT AS STALE_PCT
FROM IDENTIFIER('{DOCS_MASTER}');
